### ISSUE TITLE
Multiple input and output files

### ISSUE THREAD

**Issue by Voralberg** [jberkenbilt/debian-qpdf#1]
Good morning,
Is there a way to add the possibility to linearize multiple input files, in one directory, in output with the same name with a simple command?
Something like:
`qpdf --linearize *.pdf (something?)`

Maybe there is a way, in that case I apology for this issues, that is simple and does not involve strange bash script that I am not aware of.

**Comment by Voralberg** [comment]
Good Morning Mr. Berkenbilt,
I am new to coding so I apology for my clumsiness.
I would like to really thank you for having taken the time to answer me.
I have more or less 200 files yet to linearize, the code that you provided me:
```
mkdir out
for i in *.pdf; do qpdf --linearize $i out/$i; done
```
worked like a charm for the few files that had a simple name of one word, for all the others I get for each of 'em

```
qpdf: unknown argument The

Usage: qpdf [options] infile outfile
For detailed help, run qpdf --help
```

It's there a way to solve this problem? Most of the files have in their name the dash (-) and multiple spaces. 

I would really like to know since renaming all those files would be a real bummer.

Thank you in advance.

**Comment by jberkenbilt** [comment]
This just requires proper quoting. Use this instead:

```
for i in *.pdf; do qpdf --linearize "$i" "out/$i"; done
```

With the quoting, the shell will consider the spaces as part of the arguments rather than as argument separators.

**Comment by Voralberg** [comment]
I tought that it had to do with the quote, but my attempts were all in the wrong direction.

You've saved me a lot of time, for that I thank you.
I wish you a good day.
Till the next time
